Refactor for consistent spacing, indentation, and syntax
emilyjmiles/fitlit-group-project pull request #39
Opened 2022-09-12 22:39 UTC by emilyjmiles

## Type of change

- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Refactor

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [ ] I tested my changes in the browser
- [ ] I tested with Mocha/Chai

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new bugs
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Is your code D.R.Y?
- [ ] Does it follow SRP?

2022-09-12 22:53 UTC, ohClaire commented on src/apiCalls.js
>  export default fetchData
add semicolon here

2022-09-12 22:55 UTC, ohClaire requested changes
Please add semicolon in apiCalls file

2022-09-13 15:13 UTC, emilyjmiles commented on src/apiCalls.js
>  export default fetchData
Semi colon added in green block!

2022-09-13 15:24 UTC, ohClaire approved these changes

2022-09-13 15:25 UTC, merged